Importing Libraries

In [0]:
from google.colab import drive
drive.mount('/content/drive')

In [0]:
import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout
from keras.utils import np_utils

Using TensorFlow backend.


Reading working file from Google drive

In [0]:
df = pd.read_csv('/content/drive/My Drive/Data Science/sensor_readings_24.csv', header=None)
df.head()

0      1      2      3   ...     21     22     23                 24
0  0.438  0.498  3.625  3.645  ...  0.444  0.440  0.429  Slight-Right-Turn
1  0.438  0.498  3.625  3.648  ...  0.444  0.443  0.429  Slight-Right-Turn
2  0.438  0.498  3.625  3.629  ...  0.444  0.446  0.429  Slight-Right-Turn
3  0.437  0.501  3.625  3.626  ...  0.444  0.444  0.429  Slight-Right-Turn
4  0.438  0.498  3.626  3.629  ...  0.444  0.441  0.429  Slight-Right-Turn

[5 rows x 25 columns]

Exploratory Data  Analysis

In [0]:
df.describe()

0            1   ...           22           23
count  5456.000000  5456.000000  ...  5456.000000  5456.000000
mean      1.471617     2.327043  ...     1.555045     1.578508
std       0.802801     1.410146  ...     1.291447     1.150480
min       0.400000     0.437000  ...     0.367000     0.377000
25%       0.921000     1.362000  ...     0.792000     0.884000
50%       1.335000     1.904500  ...     1.071000     1.289000
75%       1.814000     2.681500  ...     1.559500     1.657250
max       5.000000     5.025000  ...     5.000000     5.000000

[8 rows x 24 columns]

In [0]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
dtype: int64

In [0]:
df.shape

(5456, 25)

In [0]:
df[24].describe()

count             5456
unique               4
top       Move-Forward
freq              2205
Name: 24, dtype: object

In [0]:
df[24].unique()

array(['Slight-Right-Turn', 'Sharp-Right-Turn', 'Move-Forward',
       'Slight-Left-Turn'], dtype=object)

In [0]:
len(df.columns)

25

In [0]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

X.shape, y.shape

((5456, 24), (5456,))

Standardising features

In [0]:
sc = StandardScaler()
X = sc.fit_transform(X)
X.shape

(5456, 24)

In [0]:
print(X)

[[-1.28763174 -1.29717819  0.91047428 ... -0.8488698  -0.86348656
  -0.99924691]
 [-1.28763174 -1.29717819  0.91047428 ... -0.8488698  -0.86116338
  -0.99924691]
 [-1.28763174 -1.29717819  0.91047428 ... -0.8488698  -0.85884019
  -0.99924691]
 ...
 [-0.66600116  1.89569183  1.23837723 ...  2.05019466  2.66775906
  -0.41161214]
 [-0.65603514  1.22335936  1.25280817 ...  2.05019466  2.66775906
  -0.40031147]
 [-0.64980637  1.23328832  2.0128375  ...  2.05019466  2.66775906
  -0.35684736]]


Label Encoding

In [0]:
le = LabelEncoder()
y = le.fit_transform(y)
y

array([3, 3, 3, ..., 1, 0, 1])

Splitting Features and Labels as Train and Test dataset

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=0)

X_train

array([[-0.64357761, -0.45818102, -0.67292015, ..., -0.53389243,
        -0.48558133, -0.55765155],
       [ 1.31848284,  0.15315926, -0.33539658, ...,  1.13262421,
         2.66775906,  0.84189281],
       [ 0.74917387, -0.16031221, -0.27526768, ...,  0.17878364,
         0.37787018,  0.41333668],
       ...,
       [-0.0094895 ,  0.11628026,  0.00373043, ..., -0.21000661,
        -0.09063939, -0.11344834],
       [ 0.72301306, -0.19506357, -0.36506017, ...,  0.16478465,
         0.36547984,  0.40551314],
       [ 1.25245795,  0.01557224, -0.62000672, ...,  1.23188981,
         2.66775906,  0.7201933 ]])

In [0]:
y_train = np_utils.to_categorical(y_train,4)
y_test = np_utils.to_categorical(y_test,4)

y_train[0]

array([1., 0., 0., 0.], dtype=float32)

Building Neaural Network

In [0]:
model = Sequential()

In [0]:
model.add(Dense(units=32, input_shape=(24,)))
#model.add(Dropout(0.2))
model.add(BatchNormalization())

model.add(Dense(units=64, activation='relu'))
#model.add(Dropout(0.2))

model.add(Dense(units=128, activation='relu'))
#model.add(Dropout(0.3))

model.add(Dense(units=4, activation='softmax'))


In [0]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                800       
_________________________________________________________________
batch_normalization (BatchNo (None, 32)                128       
_________________________________________________________________
dense_1 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_2 (Dense)              (None, 128)               8320      
_________________________________________________________________
dense_3 (Dense)              (None, 4)                 516       
Total params: 11,876
Trainable params: 11,812
Non-trainable params: 64
_________________________________________________________________


In [0]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [0]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),batch_size=200,epochs=10)

Epoch 1/10
20/20 [==============================] - 0s 12ms/step - loss: 1.1704 - accuracy: 0.4459 - val_loss: 0.9676 - val_accuracy: 0.5822
Epoch 2/10
20/20 [==============================] - 0s 5ms/step - loss: 0.8627 - accuracy: 0.6216 - val_loss: 0.8031 - val_accuracy: 0.6762
Epoch 3/10
20/20 [==============================] - 0s 5ms/step - loss: 0.7186 - accuracy: 0.7099 - val_loss: 0.7060 - val_accuracy: 0.7202
Epoch 4/10
20/20 [==============================] - 0s 4ms/step - loss: 0.6451 - accuracy: 0.7434 - val_loss: 0.6444 - val_accuracy: 0.7337
Epoch 5/10
20/20 [==============================] - 0s 5ms/step - loss: 0.5691 - accuracy: 0.7683 - val_loss: 0.6052 - val_accuracy: 0.7563
Epoch 6/10
20/20 [==============================] - 0s 5ms/step - loss: 0.5259 - accuracy: 0.7905 - val_loss: 0.5614 - val_accuracy: 0.7715
Epoch 7/10
20/20 [==============================] - 0s 5ms/step - loss: 0.4868 - accuracy: 0.8112 - val_loss: 0.5349 - val_accuracy: 0.7935
Epoch 8/10
20/20 [=

In [0]:
y_pred = model.predict(X_test)
y_pred = y_pred > 0.5

Accuracy of model

In [0]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test,y_pred,normalize=True)

print('Accuracy score of model : %d%%' %(score*100))

Accuracy score of model : 79%
